# Generated by Django 5.2.12 on 2026-03-31 08:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chambers',
            },
        ),
        migrations.CreateModel(
            name='GenericMedicineModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('drug_class', models.CharField(db_index=True, max_length=100)),
                ('contraindications', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'generic_medicines',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('assistant_doctor', 'Assistant Doctor'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant')], db_index=True, default='receptionist', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('chambers', models.ManyToManyField(blank=True, related_name='staff', to='infrastructure.chambermodel')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('appointment_type', models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow Up'), ('walk_in', 'Walk In')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_queue', 'In Queue'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('token_number', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.chambermodel')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='ConsultationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chief_complaints', models.TextField()),
                ('clinical_findings', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='infrastructure.appointmentmodel')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
        migrations.CreateModel(
            name='BrandMedicineModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='infrastructure.genericmedicinemodel')),
            ],
            options={
                'db_table': 'brand_medicines',
            },
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='infrastructure.consultationmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='infrastructure.invoicemodel')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('allergies', models.JSONField(default=list)),
                ('chronic_diseases', models.JSONField(default=list)),
                ('family_history', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'indexes': [models.Index(fields=['full_name'], name='patients_full_na_4556a3_idx'), models.Index(fields=['phone'], name='patients_phone_ef6690_idx'), models.Index(fields=['patient_id'], name='patients_patient_e63b14_idx'), models.Index(fields=['created_at'], name='patients_created_b2d3e4_idx')],
            },
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='infrastructure.patientmodel'),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='infrastructure.patientmodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='infrastructure.patientmodel'),
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='infrastructure.invoicemodel')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='infrastructure.consultationmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='infrastructure.patientmodel')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('morning', models.CharField(max_length=10)),
                ('afternoon', models.CharField(max_length=10)),
                ('evening', models.CharField(max_length=10)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('route', models.CharField(default='oral', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.brandmedicinemodel')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='infrastructure.prescriptionmodel')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='TestOrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('lab_name', models.CharField(blank=True, max_length=255)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_orders', to='infrastructure.consultationmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_orders', to='infrastructure.patientmodel')),
            ],
            options={
                'db_table': 'test_orders',
            },
        ),
        migrations.CreateModel(
            name='ReportDocumentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('blood_test', 'Blood Test'), ('imaging', 'Imaging'), ('biopsy', 'Biopsy'), ('other', 'Other')], db_index=True, max_length=30)),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='infrastructure.consultationmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='infrastructure.patientmodel')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='infrastructure.testordermodel')),
            ],
            options={
                'db_table': 'report_documents',
            },
        ),
        migrations.CreateModel(
            name='AuditLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.CharField(db_index=True, max_length=36)),
                ('payload', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='brandmedicinemodel',
            index=models.Index(fields=['brand_name', 'is_active'], name='brand_medic_brand_n_422ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='brandmedicinemodel',
            index=models.Index(fields=['generic', 'is_active'], name='brand_medic_generic_ea263a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['created_at', 'status'], name='invoices_created_e66d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['patient', 'created_at'], name='invoices_patient_d3ed62_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationmodel',
            index=models.Index(fields=['patient', 'created_at'], name='consultatio_patient_ebc6af_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationmodel',
            index=models.Index(fields=['diagnosis'], name='consultatio_diagnos_beb645_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmodel',
            index=models.Index(fields=['scheduled_at', 'status'], name='appointment_schedul_1236ec_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmodel',
            index=models.Index(fields=['patient', 'scheduled_at'], name='appointment_patient_e2b773_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmodel',
            index=models.Index(fields=['doctor', 'scheduled_at'], name='appointment_doctor__b1e0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentmodel',
            index=models.Index(fields=['chamber', 'scheduled_at'], name='appointment_chamber_cf95e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdocumentmodel',
            index=models.Index(fields=['patient', 'uploaded_at'], name='report_docu_patient_1b4168_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdocumentmodel',
            index=models.Index(fields=['category'], name='report_docu_categor_42fecb_idx'),
        ),
    ]
