# Generated by Django 5.2.12 on 2026-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('assistant_doctor', 'Assistant Doctor'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant')], db_index=True, default='receptionist', max_length=30),
        ),
    ]
