# Generated by Django 5.2.12 on 2026-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_add_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('assistant_doctor', 'Assistant Doctor'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant')], db_index=True, default='receptionist', max_length=30),
        ),
    ]
