# Generated by Django 5.2.12 on 2026-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_chamber_gps_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
