# Generated by Django 5.2.12 on 2026-04-06 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_patient_phone_allow_duplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'specialities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualifications', models.CharField(help_text='e.g. MBBS, MD (Cardiology), FCPS', max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('visit_days', models.JSONField(blank=True, default=list, help_text='e.g. ["Sat", "Sun", "Mon"]')),
                ('visit_time_start', models.TimeField(blank=True, null=True)),
                ('visit_time_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='infrastructure.specialitymodel')),
            ],
            options={
                'db_table': 'doctor_profiles',
                'indexes': [models.Index(fields=['speciality', 'is_available'], name='doctor_prof_special_e3a06f_idx')],
            },
        ),
    ]
