# Generated by Django 5.2.12 on 2026-04-15 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_doctor_profile_and_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('country', models.CharField(blank=True, default='Bangladesh', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['name'],
            },
        ),
    ]
